name: noyobo/prettier-bot
description: Prettier pull request changed files.
author: noyobo

branding:
  icon: check-circle
  color: purple

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  prettier-ignore:
    description: The path to the prettier ignore file
    default: .prettierignore
    required: false

outputs:
  exitCode:
    description: 'The exit code of the prettier command'

runs:
  using: node20
  main: dist/index.js
