name: Prettier Bot
description: Prettier pull request changed files.
author: noyobo

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: #000000

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

outputs:
  exitCode:
    description: 'The exit code of the prettier command'

runs:
  using: node20
  main: dist/index.js
