name: noyobo/prettier-bot
description: Prettier pull request changed files.
author: noyobo

branding:
  icon: check-circle
  color: purple

inputs:
  github_token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  prettier_ignore:
    description: The path to the prettier ignore file
    default: .prettierignore
    required: false
  prettier_version:
    description: The version of prettier to install
    default: 3.x
    required: false

outputs:
  exitCode:
    description: 'The exit code of the prettier command'

runs:
  using: 'node20'
  main: 'dist/index.js'
